### ISSUE TITLE
Calling `WK.getRadicals()` throws `Uncaught TypeError: Cannot read property 'split' of undefined`

### ISSUE THREAD

**Issue by zosiu** [takakoshimizu/wanikani-api#4]
I would like to get all the radicals (as well as kanji and vocab) available for a given user.

According to the WK API docs:

> If the levels argument is not specified, then all levels up to the user's level will be returned.

It would be nice if the function could be called without a parameter.

**Comment by takakoshimizu** [comment]
Fix in progress. Maybe a little refactoring to allow this across the board.

**Comment by takakoshimizu** [comment]
Feature implemented via PR #5.
